version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install
      - touch database/database.sqlite
      - DB_CONNECTION=sqlite CACHE_DRIVER=file php artisan migrate --force

  post_build:
    commands:
      - echo Build completed on `date`
      - ./vendor/bin/phpunit --configuration ./phpunit.xml