version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install --no-dev

  post_build:
    commands:
      - echo Build completed on `date`
      - php ./vendor/phpunit/phpunit/phpunit --configuration ./phpunit.xml