version: 0.2
phases:
  install:
    commands:
      - apt-get install -y sqlite3

  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install
      - touch database/database.sqlite
      - php artisan migrate --database=sqlite --force

  post_build:
    commands:
      - echo Build completed on `date`
      - ./vendor/bin/phpunit --configuration ./phpunit.xml