version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install --no-dev

  post_build:
    commands:
      - echo Build completed on `date`
      - ./vendor/bin/phpunit --configuration ./phpunit.xml